// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3AssetChain {
  // https://scan.assetchain.org/address/0x03D8eE30a660B02310F45516677Df664f26dDed0
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x03D8eE30a660B02310F45516677Df664f26dDed0);

  // https://scan.assetchain.org/address/0xf4A505a261A3B70c8632FB2772D73F3dDe62399E
  IPool internal constant POOL = IPool(0xf4A505a261A3B70c8632FB2772D73F3dDe62399E);

  // https://scan.assetchain.org/address/0xDad2dbCAae132E7A0a76F3dfB6C3383A51875019
  address internal constant POOL_IMPL = 0xDad2dbCAae132E7A0a76F3dfB6C3383A51875019;

  // https://scan.assetchain.org/address/0xcb919BF48D2E123C6b70650E2bf0b2A7D3EDc36A
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0xcb919BF48D2E123C6b70650E2bf0b2A7D3EDc36A);

  // https://scan.assetchain.org/address/0x4fF7C67f038863Cf70a211b4B82C051Bd3c346bc
  address internal constant POOL_CONFIGURATOR_IMPL = 0x4fF7C67f038863Cf70a211b4B82C051Bd3c346bc;

  // https://scan.assetchain.org/address/0x703a6a9bAe24fdAa8ff1e9fd2b79691B332846d7
  IAaveOracle internal constant ORACLE = IAaveOracle(0x703a6a9bAe24fdAa8ff1e9fd2b79691B332846d7);

  // https://scan.assetchain.org/address/0x1d0c5587b05D2FBE944c118d581C3102E06D1726
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x1d0c5587b05D2FBE944c118d581C3102E06D1726);

  // https://scan.assetchain.org/address/0x6A23fDabCF6fA132f18e567275568219C2a75239
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x6A23fDabCF6fA132f18e567275568219C2a75239);

  // https://scan.assetchain.org/address/0x54527B09Aeb2Be23F99958Db8f2f827daB863A28
  address internal constant ACL_ADMIN = 0x54527B09Aeb2Be23F99958Db8f2f827daB863A28;

  // https://scan.assetchain.org/address/0xE09A5eee7c6d4Ab76e663BBF6B2d28218852d554
  ICollector internal constant COLLECTOR = ICollector(0xE09A5eee7c6d4Ab76e663BBF6B2d28218852d554);

  // https://scan.assetchain.org/address/0x0C5048A29be1754D4420B609f484FD14679Adde1
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x0C5048A29be1754D4420B609f484FD14679Adde1;

  // https://scan.assetchain.org/address/0xad64C693313B8E3f7bdADfd3F027007e2df8f97a
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0xad64C693313B8E3f7bdADfd3F027007e2df8f97a;

  // https://scan.assetchain.org/address/0x9C72D91bFdE57159f0B13199BD70298c969Bc1B0
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x9C72D91bFdE57159f0B13199BD70298c969Bc1B0;

  // https://scan.assetchain.org/address/0x5792F611b7b60FA010Ca7ba3B2B96c4Fc01cf825
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x5792F611b7b60FA010Ca7ba3B2B96c4Fc01cf825;

  // https://scan.assetchain.org/address/0x31409B7d7BD5C4Ab1EcD8879DAf70a5eb0aAd586
  address internal constant EMISSION_MANAGER = 0x31409B7d7BD5C4Ab1EcD8879DAf70a5eb0aAd586;

  // https://scan.assetchain.org/address/0xb8761622587aE3E322FDE8994Ecd9a6f6F6336E8
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0xb8761622587aE3E322FDE8994Ecd9a6f6F6336E8;

  // https://scan.assetchain.org/address/0xd1B885868acf06D242D0E7d127e94af343B2E08D
  address internal constant UI_POOL_DATA_PROVIDER = 0xd1B885868acf06D242D0E7d127e94af343B2E08D;

  // https://scan.assetchain.org/address/0x2041caE7dDe0188F0bA6Ba5Ff357a8Df658D93bA
  address internal constant WALLET_BALANCE_PROVIDER = 0x2041caE7dDe0188F0bA6Ba5Ff357a8Df658D93bA;

  // https://scan.assetchain.org/address/0xF9e09d45007a9DE3d897Cb2813D70A3FDA2A51b2
  address internal constant WETH_GATEWAY = 0xF9e09d45007a9DE3d897Cb2813D70A3FDA2A51b2;

  // https://scan.assetchain.org/address/0x2DAE67e37FA80ed225c8E88a161e06F484886838
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0x2DAE67e37FA80ed225c8E88a161e06F484886838;
}

library AaveV3AssetChainAssets {
  // https://scan.assetchain.org/address/0x2B7C1342Cc64add10B2a79C8f9767d2667DE64B2
  address internal constant USDC_UNDERLYING = 0x2B7C1342Cc64add10B2a79C8f9767d2667DE64B2;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://scan.assetchain.org/address/0x4f7bd8Be60c1652BEC4a7D798F936C1A8031098a
  address internal constant USDC_A_TOKEN = 0x4f7bd8Be60c1652BEC4a7D798F936C1A8031098a;

  // https://scan.assetchain.org/address/0xb319873f820fd35590a1e4F19C09dD20BeF42d8b
  address internal constant USDC_V_TOKEN = 0xb319873f820fd35590a1e4F19C09dD20BeF42d8b;

  // https://scan.assetchain.org/address/0x693ead553A9a66251a4B95bD1aB7e3d5d5A57E30
  address internal constant USDC_S_TOKEN = 0x693ead553A9a66251a4B95bD1aB7e3d5d5A57E30;

  // https://scan.assetchain.org/address/0xf0Ec014Fde27e864C885cd433E1a76765f37d149
  address internal constant USDC_ORACLE = 0xf0Ec014Fde27e864C885cd433E1a76765f37d149;

  // https://scan.assetchain.org/address/0x68BB6616b7f12b2EF7650dFf84febcAcd342c82e
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x68BB6616b7f12b2EF7650dFf84febcAcd342c82e;

  // https://scan.assetchain.org/address/0x2584D40B5553E81Bb9deC0b6CD1a2E504AAB1709
  address internal constant WRWA_UNDERLYING = 0x2584D40B5553E81Bb9deC0b6CD1a2E504AAB1709;

  uint8 internal constant WRWA_DECIMALS = 18;

  // https://scan.assetchain.org/address/0xF7770C8E1a38ff891c090eE523D6C8F209bB13c1
  address internal constant WRWA_A_TOKEN = 0xF7770C8E1a38ff891c090eE523D6C8F209bB13c1;

  // https://scan.assetchain.org/address/0x58075Fb21d29D3Bf0d326548de6cCbe1c28e6eb0
  address internal constant WRWA_V_TOKEN = 0x58075Fb21d29D3Bf0d326548de6cCbe1c28e6eb0;

  // https://scan.assetchain.org/address/0xc6Ad542b13eD30382Dbe0Cd218C0aAC272a723F7
  address internal constant WRWA_S_TOKEN = 0xc6Ad542b13eD30382Dbe0Cd218C0aAC272a723F7;

  // https://scan.assetchain.org/address/0x9794D8B3152aaD47790332Ae4695901a9F826d54
  address internal constant WRWA_ORACLE = 0x9794D8B3152aaD47790332Ae4695901a9F826d54;

  // https://scan.assetchain.org/address/0xf4343f46B617e94D01e2de385F1F2c70393bbD72
  address internal constant WRWA_INTEREST_RATE_STRATEGY =
    0xf4343f46B617e94D01e2de385F1F2c70393bbD72;

  // https://scan.assetchain.org/address/0x26E490d30e73c36800788DC6d6315946C4BbEa24
  address internal constant USDT_UNDERLYING = 0x26E490d30e73c36800788DC6d6315946C4BbEa24;

  uint8 internal constant USDT_DECIMALS = 18;

  // https://scan.assetchain.org/address/0x29DE0461FAC747f78fE2e89ceb9fa9a3a23F0930
  address internal constant USDT_A_TOKEN = 0x29DE0461FAC747f78fE2e89ceb9fa9a3a23F0930;

  // https://scan.assetchain.org/address/0xeF08802e9DD28b82dc7139e2f0616E826D31D3D0
  address internal constant USDT_V_TOKEN = 0xeF08802e9DD28b82dc7139e2f0616E826D31D3D0;

  // https://scan.assetchain.org/address/0xf8556270C8425E3c5D9662855c7C2C14eDb47cef
  address internal constant USDT_S_TOKEN = 0xf8556270C8425E3c5D9662855c7C2C14eDb47cef;

  // https://scan.assetchain.org/address/0x67b9f799c354e3602A7a55F62F37192ced9f8fd0
  address internal constant USDT_ORACLE = 0x67b9f799c354e3602A7a55F62F37192ced9f8fd0;

  // https://scan.assetchain.org/address/0x68BB6616b7f12b2EF7650dFf84febcAcd342c82e
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x68BB6616b7f12b2EF7650dFf84febcAcd342c82e;
}

library AaveV3AssetChainEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant STABLECOINS = 1;
}
