// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3AssetChainTestnet {
  // https://scan-testnet.assetchain.org/address/0x14B1e694C1ec6709E853D2Aa6F9fD82771883612
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x14B1e694C1ec6709E853D2Aa6F9fD82771883612);

  // https://scan-testnet.assetchain.org/address/0x4adE67AB8153d1661ce133bdB9DaEF05fa94bb19
  IPool internal constant POOL = IPool(0x4adE67AB8153d1661ce133bdB9DaEF05fa94bb19);

  // https://scan-testnet.assetchain.org/address/0x74FE522656b5D06104c4c335F6e1447d7E611625
  address internal constant POOL_IMPL = 0x74FE522656b5D06104c4c335F6e1447d7E611625;

  // https://scan-testnet.assetchain.org/address/0x2bB4CAD0Bd25c35035f26CB56a0eb2dA6638B832
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x2bB4CAD0Bd25c35035f26CB56a0eb2dA6638B832);

  // https://scan-testnet.assetchain.org/address/0x7239c198304dC9F462A89f957A8CA9a2ce088647
  address internal constant POOL_CONFIGURATOR_IMPL = 0x7239c198304dC9F462A89f957A8CA9a2ce088647;

  // https://scan-testnet.assetchain.org/address/0xf70B17e07E429f84f4652237901356aBE4810d1A
  IAaveOracle internal constant ORACLE = IAaveOracle(0xf70B17e07E429f84f4652237901356aBE4810d1A);

  // https://scan-testnet.assetchain.org/address/0xB807cD39b37f728Bb403fEAa5839F382975487eC
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0xB807cD39b37f728Bb403fEAa5839F382975487eC);

  // https://scan-testnet.assetchain.org/address/0x49861fdcF78E2D9D5d8fC553F683620211230C20
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x49861fdcF78E2D9D5d8fC553F683620211230C20);

  // https://scan-testnet.assetchain.org/address/0x5dAA96364bD8e0c4f95004ADb4bDe0F2aFe933C9
  address internal constant ACL_ADMIN = 0x5dAA96364bD8e0c4f95004ADb4bDe0F2aFe933C9;

  // https://scan-testnet.assetchain.org/address/0xa7F8425F03B3a977fd9A55FbCacc43D7232e02Fd
  ICollector internal constant COLLECTOR = ICollector(0xa7F8425F03B3a977fd9A55FbCacc43D7232e02Fd);

  // https://scan-testnet.assetchain.org/address/0x403310ED9EE091334Cc379fe931c1203e675dbDe
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x403310ED9EE091334Cc379fe931c1203e675dbDe;

  // https://scan-testnet.assetchain.org/address/0xe245AAf4D0ab01b24074Dd42fd37a0f20dA258aE
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0xe245AAf4D0ab01b24074Dd42fd37a0f20dA258aE;

  // https://scan-testnet.assetchain.org/address/0x1c972B7EB8d6fC0aEE5A7a5DfD9D6343953a4058
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x1c972B7EB8d6fC0aEE5A7a5DfD9D6343953a4058;

  // https://scan-testnet.assetchain.org/address/0xd5809bd96Ec4663f90f6cF7EEEcC506aec202BAF
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xd5809bd96Ec4663f90f6cF7EEEcC506aec202BAF;

  // https://scan-testnet.assetchain.org/address/0xc73b957f0aB26f3CF7016c25866F622357fdAe3b
  address internal constant EMISSION_MANAGER = 0xc73b957f0aB26f3CF7016c25866F622357fdAe3b;

  // https://scan-testnet.assetchain.org/address/0xa8b5437E8f937290B83576B726AC20C5ffA545EB
  address internal constant FAUCET = 0xa8b5437E8f937290B83576B726AC20C5ffA545EB;

  // https://scan-testnet.assetchain.org/address/0x4258D81B9008ed939854e84e4530eaBD2F09dc8e
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x4258D81B9008ed939854e84e4530eaBD2F09dc8e;

  // https://scan-testnet.assetchain.org/address/0xAfaAdE68D2F614B8aaf9c7587EABd44B3033A31e
  address internal constant UI_POOL_DATA_PROVIDER = 0xAfaAdE68D2F614B8aaf9c7587EABd44B3033A31e;

  // https://scan-testnet.assetchain.org/address/0xd567E376935f1Df99Bc80ad22Dc52331B7C91fA0
  address internal constant WALLET_BALANCE_PROVIDER = 0xd567E376935f1Df99Bc80ad22Dc52331B7C91fA0;

  // https://scan-testnet.assetchain.org/address/0x0fd722E31a1319f365a7225a28798919F1aFdC9D
  address internal constant WETH_GATEWAY = 0x0fd722E31a1319f365a7225a28798919F1aFdC9D;

  // https://scan-testnet.assetchain.org/address/0x74b31d8542AB85898e57b55C8DDA0Ba1631a12B5
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0x74b31d8542AB85898e57b55C8DDA0Ba1631a12B5;
}

library AaveV3AssetChainTestnetAssets {
  // https://scan-testnet.assetchain.org/address/0x1eB7D569e3D41cF25A20090882A9d6F02c1e6225
  address internal constant WRWA_UNDERLYING = 0x1eB7D569e3D41cF25A20090882A9d6F02c1e6225;

  uint8 internal constant WRWA_DECIMALS = 18;

  // https://scan-testnet.assetchain.org/address/0xdd5dd82215e9F3C1fa69AF565A898B96967c5Fa7
  address internal constant WRWA_A_TOKEN = 0xdd5dd82215e9F3C1fa69AF565A898B96967c5Fa7;

  // https://scan-testnet.assetchain.org/address/0x10732394FF614ec67f4ba9023a116F8419CF7DC0
  address internal constant WRWA_V_TOKEN = 0x10732394FF614ec67f4ba9023a116F8419CF7DC0;

  // https://scan-testnet.assetchain.org/address/0xFA24147862cc2854acbccBc39df0Cd9CB16D3a2f
  address internal constant WRWA_S_TOKEN = 0xFA24147862cc2854acbccBc39df0Cd9CB16D3a2f;

  // https://scan-testnet.assetchain.org/address/0x16910Ac6714A1491a95C6C038b6F9A670B9F4F8d
  address internal constant WRWA_ORACLE = 0x16910Ac6714A1491a95C6C038b6F9A670B9F4F8d;

  // https://scan-testnet.assetchain.org/address/0xdeB434D448452D6ce29662DA68D4C247EA48F2F4
  address internal constant WRWA_INTEREST_RATE_STRATEGY =
    0xdeB434D448452D6ce29662DA68D4C247EA48F2F4;
}

library AaveV3AssetChainTestnetEModes {
  uint8 internal constant NONE = 0;
}
