// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscAssetChain {
  // https://scan.assetchain.org/address/0x54527B09Aeb2Be23F99958Db8f2f827daB863A28
  address internal constant PROXY_ADMIN = 0x54527B09Aeb2Be23F99958Db8f2f827daB863A28;
}
