// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscAssetChainTestnet {
  // https://scan-testnet.assetchain.org/address/0x43A8B7eC945a12a3Acb127B77ede19bd73ad76f8
  address internal constant TRANSPARENT_PROXY_FACTORY = 0x43A8B7eC945a12a3Acb127B77ede19bd73ad76f8;

  // https://scan-testnet.assetchain.org/address/0xCB5B3ca20603231945dC5731C33E7f7F7679Ea89
  address internal constant PROXY_ADMIN = 0xCB5B3ca20603231945dC5731C33E7f7F7679Ea89;
}
